[dev-011]セクションの作成
penguin-syan/PHP-Form-4-Expt pull request #54
Opened 2022-06-11 21:47 UTC by akihiro21

**変更の概要**  
複数の質問をまとめて扱うセクションを作成するための関数の追加

**変更理由**  
複数の質問をまとめて扱うセクションの実装

**変更内容**  
group_sectionとrandom_sectionの追加

**課題**  
コールバック関数の実装の都合上、関数をそのまま代入することは難しいため、[string 関数名, 実行する関数の引数]を引数として実装した。そのため、要件と少し差異があり、引数が少し理解しにくい。

一応以下のように使用はできる。

```
  $group1 = ["random_section",
              [
                ['video','./movie.mp4', ObjectSize::SMALL_FULL , 3],
                ["likert_scale",'次のうち当てはまるものを選択してください．','迷わず，直感的に選択してください',['非常に同意する', '同意する', 'やや同意する', 'どちらともいえない', 'やや同意しない', '同意しない', '全く同意しない'],true],
                ["video",'./movie.mp4', ObjectSize::SMALL, 1]
              ]
            ];
 
  $group2 = ["random_section",
              [
                ['video','./movie.mp4', ObjectSize::SMALL_FULL , 3],
                ["likert_scale",'次のうち当てはまるものを選択してください．','迷わず，直感的に選択してください',['非常に同意する', '同意する', 'やや同意する', 'どちらともいえない', 'やや同意しない', '同意しない', '全く同意しない'],true],
                ["video",'./movie.mp4', ObjectSize::SMALL, 1]
              ]
            ];
 
  group_section([$group1,$group2]);
```

**備考**  
もうちょっと上手く実装できないかなと思ったけど、phpの機能的に今の感じになるかなと思う。いいアイディアがあれば変更してもいいかも。

2022-06-13 03:49 UTC, penguin-syan commented
@akihiro21 
確かに，もうちょっとうまく実装できないかなという気持ちも，他の処理が思いつかないという気持ちも分かる…w
案があるとすれば，各関数を指定する配列を直接書かずにインスタンス化で書く感じかね…
```php
// 現行案
["likert_scale",'次のうち当てはまるものを選択してください．','迷わず，直感的に選択してください',['<選択肢（省略）>'],true]

// 代案
// インスタンス化の結果，返り値として得られるものは現行案の配列と同じ
new likert_scale('次のうち当てはまるものを選択してください’,'迷わず，直観的に選択してください',['<選択肢（省略）>'],true)
```

結局インスタンス化した結果として得られるものは同じ配列なので，group_section関数自体の処理は変わらない．
ただ，インスタンス化という工程を挟むことでエディタの入力補助？（引数の意味が出てくるやつ）が使えたり，
エラーの内容がわかりやすくなると思うので，多少は使いやすくなるかもという感じ．

丁度いま，各機能の関数が単体で存在するので，クラスにまとめるとuseの数が減ってよいかもしれない．
↓イメージ
```php
class likert_scale {
  // コンストラクタ
  // 引数を基にセクション用の配列を返す
  public function __construct(string question...) {
    return [question, ...]
  }

  // これは既に作成したやつ
  public static function likert_scale(...) {}
}
```

2022-06-13 03:50 UTC, penguin-syan commented
上記の案をやるなら，開発時のデバッグに必要そうな分（video関数とlikert_scale関数の2つかな？）だけ
クラスにまとめてもらって，他の奴は別タスクとして出します．

2022-06-13 10:13 UTC, penguin-syan reviewed
PHPdoc用のコメントがない｡ﾟ(ﾟ´ω`ﾟ)ﾟ｡ﾋﾟｰ

2022-06-13 10:15 UTC, akihiro21 commented
忘れてたー
追記しときます

2022-06-13 10:24 UTC, penguin-syan commented
あと，`random_section::random_section()`正常に動いてる…？
`group_section()`のほうでは問題なかったんだけど，`random_section()`に変えると最初の要素しか出力されないんだけど…

2022-06-13 10:29 UTC, penguin-syan commented
ごめん動いた，僕が書きミスってた

2022-06-13 10:30 UTC, akihiro21 commented
引数が配列になってなかったり、おかしいところない？
処理的にはシャッフル追加しただけなんだけど

2022-06-13 10:30 UTC, penguin-syan requested changes
**修正内容**  
PHPdocに対応したコメントだけ追加してください．
それ以外の動作は問題なさそうです．

2022-06-13 10:30 UTC, akihiro21 commented
了解👌

2022-06-13 11:42 UTC, akihiro21 commented
phpdoc追加したのでチェックお願いします！

2022-06-14 05:07 UTC, penguin-syan approved these changes

2022-06-14 05:08 UTC, penguin-syan approved these changes

2022-06-14 05:08 UTC, merged