dev-010
penguin-syan/PHP-Form-4-Expt pull request #64
Opened 2022-07-01 06:15 UTC by mkei0719

**変更の概要**  
Textbox.php（Textboxクラス，textbox関数，textbox_array関数）及びInputTextType.phpの追加．

**変更理由**  
自由記述形式の質問を扱えるようにするため．

**変更内容**  
・Textbox.php（Textboxクラス，textbox関数，textbox_array関数）及びInputTextType.phpの追加．
・textbox関数の引数max_lengthとmin_lengthの型をintからfloatに変更．

**課題**  
・入力された文字列に対するエスケープ処理には未対応
・$max_lengthと$min_lengthの型にdoubleではなくfloatを使用しているためか，入力形式が少数で例えば数値範囲が5~10とした場合，4.9」や「10.1」と入力した場合にはエラーが出るが「4.9999999999999」や「10.00000000000001」と入力すると切り上げ・切り捨てによる誤差は発生しエラーが出ない．

**備考**  
・引数max_lengthとmin_lengthの型をintからfloatに変更．
・要デバッグ（こちらでも確認できるところまでは確認した）

2022-07-01 08:39 UTC, penguin-syan requested changes
以下の修正お願いします．
・エラー1ヶ所
・仕様ミス2ヶ所
・コメントの改良2ヶ所

2022-07-01 08:39 UTC, penguin-syan commented on src/Textbox.php
> +    public function textbox(string $question, string $supplement, int $type, float $max_length, bool $required, float $min_length = 0){
ごめん，Wikiの方を書き間違えていたのだが，静的メソッドにしてください．  
```php
// 修正前
public function textbox(...) {...}
// 修正後
public static function textbox(...) {...}
```

2022-07-01 08:39 UTC, penguin-syan commented on src/Textbox.php
> +    public function textbox_array(string $question, string $supplement, int $type, float $max_length, bool $required, float $min_length = 0){
ここも静的メソッドに．
```php
public function textbox_array(...) {...}
// ↓
public static function textbox_array(...) {...}
```

2022-07-01 08:39 UTC, penguin-syan commented on src/Textbox.php
> +require_once "./InputTextType.php";
これだとライブラリとして使う際に読み込めないので，以下のように変更をお願いします．
```php
// 変更前
require_once "./InputTextType.php";

//変更後
require_once __DIR__."/InputTextType.php";

2022-07-01 08:39 UTC, penguin-syan commented on src/Textbox.php
> + * @param float $max_length 最大入力可能文字数
文字数だけでなく，数値の追記をお願いします．
`最大入力可能文字数` → `入力可能な最大文字数または最大値` 的な感じ

2022-07-01 08:39 UTC, penguin-syan commented on src/Textbox.php
> + * @param float $min_length 最小入力条件文字数
ここも最大文字数と同様

2022-07-01 10:44 UTC, penguin-syan commented
そうそう、修正でプルリク閉じると先に入力してたコメント類が消えて勿体無いと思っていたのだけど、マージ元のブランチにプッシュするだけで変更を適用できるらしい

2022-07-01 10:44 UTC, penguin-syan commented
そうそう、修正でプルリク閉じると先に入力してたコメント類が消えて勿体無いと思っていたのだけど、マージ元のブランチにプッシュするだけで変更を適用できるらしい

2022-07-04 06:41 UTC, mkei0719 commented
以下の内容を修正しておきました．
・エラー1ヶ所
・仕様ミス2ヶ所
・コメントの改良2ヶ所
・FormEnd.php内のform_endメソッドをstatic化

2022-07-04 09:57 UTC, penguin-syan approved these changes

2022-07-04 09:58 UTC, merged